// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : szhaozho
Date           : Mon Jul 27 13:31:04 2020
Host           : Linux cmsbuild64.cern.ch 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 06:09:36 CEST 2018 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/szhaozho/BmesonppTMVA/CMSSW_9_4_10/src/TMVA/BmesonRun2018/tmva/train
Training events: 224
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "20" [Number of trees in the forest]
MaxDepth: "5" [Max depth of the decision tree allowed]
MinNodeSize: "5.0%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "3000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 14
Btrk1Pt                       Btrk1Pt                       Btrk1Pt                       Btrk1Pt                                                         'F'    [1.00055837631,1.97432780266]
Btrk2Pt                       Btrk2Pt                       Btrk2Pt                       Btrk2Pt                                                         'F'    [1.00140464306,2.21515226364]
abs(Btrk1Dz1/Btrk1DzError1)   Trk1DCAz                      Trk1DCAz                      Trk1DCAz                                                        'F'    [1.50580561161,538.354858398]
abs(Btrk2Dz1/Btrk2DzError1)   Trk2DCAz                      Trk2DCAz                      Trk2DCAz                                                        'F'    [1.82657217979,502.752349854]
abs(Btrk1Dxy1/Btrk1DxyError1) Trk1DCAxy                     Trk1DCAxy                     Trk1DCAxy                                                       'F'    [0.0280976071954,4.36707735062]
abs(Btrk2Dxy1/Btrk2DxyError1) Trk2DCAxy                     Trk2DCAxy                     Trk2DCAxy                                                       'F'    [0.000302027387079,4.32091617584]
abs(Btktkmass-1.019455)       MassDis                       MassDis                       MassDis                                                         'F'    [3.88182816096e-05,0.0149606904015]
BsvpvDistance/BsvpvDisErr     dls                           dls                           dls                                                             'F'    [3.37932991982,640.557556152]
Balpha                        Balpha                        Balpha                        Balpha                                                          'F'    [0.103203743696,3.02766346931]
Bd0                           dls2D                         dls2D                         dls2D                                                           'F'    [0.000210601225263,0.073913089931]
cos(Bdtheta)                  cos_Bdtheta_                  cos(Bdtheta)                  cos(Bdtheta)                                                    'F'    [-0.999743700027,0.999981224537]
Bchi2cl                       Bchi2cl                       Bchi2cl                       Bchi2cl                                                         'F'    [0.0502836890519,0.999668300152]
Btrk1Eta                      Btrk1Eta                      Btrk1Eta                      Btrk1Eta                                                        'F'    [-2.38207817078,2.39186167717]
Btrk2Eta                      Btrk2Eta                      Btrk2Eta                      Btrk2Eta                                                        'F'    [-2.3495695591,2.39278292656]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 14 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Btrk1Pt", "Btrk2Pt", "abs(Btrk1Dz1/Btrk1DzError1)", "abs(Btrk2Dz1/Btrk2DzError1)", "abs(Btrk1Dxy1/Btrk1DxyError1)", "abs(Btrk2Dxy1/Btrk2DxyError1)", "abs(Btktkmass-1.019455)", "BsvpvDistance/BsvpvDisErr", "Balpha", "Bd0", "cos(Bdtheta)", "Bchi2cl", "Btrk1Eta", "Btrk2Eta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[14];
   double fVmax[14];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[14];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.86284671361833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.76796, 0, 0, 0.317647,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.89158);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 2.87975, 0, 0, 0.300301,-99)    );
  // itree = 2
  fBoostWeights.push_back(1.62129);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 1.60311, 0, 0, 0.251017,-99)    );
  // itree = 3
  fBoostWeights.push_back(1.30049);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.82342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 0.96308, 0, 0, 0.322111,-99)    );
  // itree = 4
  fBoostWeights.push_back(2.15379);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.974755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.47007, 0, 0, 0.82502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 116.582, 1, 0, 0.513039,-99)    );
  // itree = 5
  fBoostWeights.push_back(2.6835);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.982975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
6, 0.00244893, 1, 0, 0.721135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.756749, 0, 0, 0.268275,-99)    );
  // itree = 6
  fBoostWeights.push_back(2.11964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.959863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.14969, 0, 0, 0.810125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 0.0127679, 0, 0, 0.339903,-99)    );
  // itree = 7
  fBoostWeights.push_back(1.79409);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.928149,-99) , 
NN(
0, 
0, 
-1, 0.00875498, 0, -1, 0.0675362,-99) , 
3, 56.7761, 0, 0, 0.595921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 108.054, 1, 0, 0.228438,-99)    );
  // itree = 8
  fBoostWeights.push_back(2.65799);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.984631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 102.504, 1, 0, 0.805568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 0.0121979, 0, 0, 0.313192,-99)    );
  // itree = 9
  fBoostWeights.push_back(1.75295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.804038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 0.0767184, 1, 0, 0.119581,-99)    );
  // itree = 10
  fBoostWeights.push_back(2.20524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.93766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
4, 1.77662, 0, 0, 0.180544,-99)    );
  // itree = 11
  fBoostWeights.push_back(1.72019);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.997432,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
7, 36.5357, 1, 0, 0.0884648,-99) , 
4, 1.80215, 0, 0, 0.27148,-99)    );
  // itree = 12
  fBoostWeights.push_back(1.68934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.5354, 1, 1, 0.900632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
3, 108.555, 1, 0, 0.659241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
1, 1.3598, 0, 0, 0.298813,-99)    );
  // itree = 13
  fBoostWeights.push_back(1.48206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.972961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379858,-99) , 
0, 1.26764, 1, 0, 0.848073,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.925165,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 0.0015431, 1, 0, 0.126376,-99) , 
11, 0.766213, 0, 0, 0.434123,-99)    );
  // itree = 14
  fBoostWeights.push_back(1.10594);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672959,-99) , 
NN(
0, 
0, 
-1, 2.36164, 0, -1, 0.0281087,-99) , 
0, 1.64508, 0, 0, 0.180364,-99)    );
  // itree = 15
  fBoostWeights.push_back(1.7284);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.23747, 1, 1, 0.858891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.810197, 0, 0, 0.186051,-99)    );
  // itree = 16
  fBoostWeights.push_back(5.06007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
5, 0.517943, 0, 0, 0.657793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.609559, 0, 0, 0.423416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
9, 0.00939578, 0, 0, 0.162118,-99)    );
  // itree = 17
  fBoostWeights.push_back(1.33315);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.920301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
8, 2.93407, 1, 0, 0.72818,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.869831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467567,-99) , 
5, 0.721861, 0, 0, 0.686865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
10, 0.950072, 0, 0, 0.160281,-99) , 
6, 0.00244889, 1, 0, 0.37725,-99)    );
  // itree = 18
  fBoostWeights.push_back(2.27319);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.975363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
11, 0.415848, 0, 0, 0.673637,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.936927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
2, 19.3285, 1, 0, 0.106116,-99) , 
10, 0.962102, 0, 0, 0.298742,-99)    );
  // itree = 19
  fBoostWeights.push_back(1.2006);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.840584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0,-99) , 
0, 1.03828, 1, 0, 0.0773755,-99) , 
9, 0.024196, 0, 0, 0.238911,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
